# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AYMTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AYMTest

 pod ’GooglePlaces'
pod ‘Alamofire’
pod ‘SwiftyJSON’

  target 'AYMTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AYMTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
